-- Crear usuarios para la aplicación Ferretería

-- Usuario Carlos Mota
CREATE USER cmota IDENTIFIED BY admin
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users
  CONTAINER = CURRENT;

GRANT CONNECT, RESOURCE TO cmota CONTAINER = CURRENT;

-- Usuario Kleiber Pérez
CREATE USER kperez IDENTIFIED BY 1234
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users
  CONTAINER = CURRENT;

GRANT CONNECT, RESOURCE TO kperez CONTAINER = CURRENT;

-- Usuario Vladimir Mendez
CREATE USER vmendez IDENTIFIED BY abcd
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users
  CONTAINER = CURRENT;

GRANT CONNECT, RESOURCE TO vmendez CONTAINER = CURRENT;
